<div class="header">
	<table class="centered"><tr valign="middle"><td align="center">
		<div class="content">
		
			<!--<img class="logotype need-svg" src="/img/logotype.svg" width="200" height="200" align="left" alt="Логотип КГБУ Камчатская государственная кадастровая оценка" aria-hidden="true" />
			<img class="logotype no-svg" src="/img/logotype.png" width="200" height="200" align="left" alt="Логотип КГБУ Камчатская государственная кадастровая оценка" aria-hidden="true" />-->
			
			<p class="form">КРАЕВОЕ ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ УЧРЕЖДЕНИЕ</p>
			<p class="name"><a class="name-link" href="/">КАМЧАТСКАЯ ГОСУДАРСТВЕННАЯ<br>КАДАСТРОВАЯ ОЦЕНКА</a></p>		
			<p class="form" style="margin-top: 5em"></p>
			<div class="contacts no-mobile">
				<p class="address" title="Показать нас на карте"><a href="https://2gis.ru/p_kamchatskiy/search/%D0%BF%D0%BE%D0%B3%D1%80%D0%B0%D0%BD%D0%B8%D1%87%D0%BD%D0%B0%D1%8F%2C%2019/geo/13370697048916886?queryState=center%2F158.666128%2C53.036007%2Fzoom%2F17" target="_blank">683032, Россия,<br/>Петропавловск-Камчатский,<br/> Пограничная, 19</a></p>
				<p class="phone" title="Позвонить"><a href="tel:84152304488"><i class="fa fa-phone"></i> (4152) 30-44-88</a></p>
				<p class="phone" title="Позвонить"><a href="tel:84152304844">По вопросам ГКО: <i class="fa fa-phone"></i> (4152) 30-48-44</a></p>
				<p class="email" title="Написать нам"><? safe_email('gko@kamgov.ru'); ?></p>
				<p class="address">Приём граждан осуществляется в рабочие дни: понедельник - четверг<br>с 09:30 до 16:00, перерыв с 12:30 до 13:45</p>
			</div>
			
		</div>
	</td></tr></table>
</div>