<div class="main-menu">
	
	<ul class="menu">
		<li>
			<a href="index.php">ОРГАНИЗАЦИЯ</a>
			<ul class="submenu">
				<li><a href="contacts.php">Реквизиты</a></li>
				<li><a href="documents.php">Учредительные документы</a></li>
			</ul>
		</li>
		<li><a href="Declaracia.php">ДЕКЛАРАЦИЯ</a></li>
		<li>
			<a href="Activity.php">ДЕЯТЕЛЬНОСТЬ</a>
			<ul class="submenu">
				<li><a href="ocenka.php">Государственная кадастровая оценка</a></li>
				<li><a href="remarks.php">Замечания</a></li>
				<li><a href="answer.php">Разъяснения</a></li>
				<li><a href="dispute.php">Рассмотрение споров</a></li>
				<li><a href="HotLine.php">Горячая линия</a></li>
				<li><a href="presentations.php">Презентации</a></li>
				<li><a href="analityca.php">Аналитические материалы</a></li>
				<li><a href="utd.php">Учётно-техническая документация</a></li>
				<li><a href="faq.php">Часто задаваемые вопросы</a></li>		
			</ul>
		</li>
		<li><a href="news.php">НОВОСТИ</a></li>
		<!-- <li><a href="structure.php">СТРУКТУРА</a></li> -->
		<li><a href="postletter.php">ПРИЁМНАЯ</a></li>
		<li><a href="corruption.php">О КОРРУПЦИИ</a></li>
		<li><a href="coruosel.php">ОТКРЫТЫЕ ДАННЫЕ</a></li>
	</ul>
	
</div>