<!DOCTYPE html>
<html lang="ru" id="modernizrcom" class="no-js">
<head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1"/>
	<title>КГБУ Камчатская государственная кадастровая оценка</title>
	<meta name="description" content="Официальный сайт КГБУ «Камчатская государственная кадастровая оценка»"/>
	<meta name="keywords" content="кадастровая оценка, кадастровая стоимость, Камчатский край, Петропавловск-Камчатский"/>
	
	<meta property="og:title" content="КГБУ КГКО" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="http://gko.kamgov.ru/" />
	<meta property="og:image" content="http://gko.kamgov.ru/img/og_image.jpg" />
	<meta property="og:image:type" content="image/jpeg" />
	<meta property="og:image:width" content="640" />
	<meta property="og:image:height" content="480" />
	

	<link rel="stylesheet"  href="/css/jquery-ui.css"/>
	<link rel="stylesheet"  href="/css/template2.css"/>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
	<script>$=function(a){$.h.push(a)};$.h=[];$$=$</script>
</head>
<body>
<? include 'email.inc'; ?>