<!DOCTYPE html>
<html lang="ru" id="modernizrcom" class="no-js">
<head>
	<!-- Yandex.Metrika counter 
<script type="text/javascript" >
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(53173708, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true,
        webvisor:true
   });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/53173708" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
 /Yandex.Metrika counter -->

	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1"/>
	<title>КГБУ Камчатская государственная кадастровая оценка</title>
	<meta name="description" content="Официальный сайт КГБУ «Камчатская государственная кадастровая оценка»"/>
	<meta name="keywords" content="кадастровая оценка, кадастровая стоимость, Камчатский край, Петропавловск-Камчатский"/>
	
	<meta property="og:title" content="КГБУ КГКО" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="http://gko.kamgov.ru/" />
	<meta property="og:image" content="http://gko.kamgov.ru/img/og_image.jpg" />
	<meta property="og:image:type" content="image/jpeg" />
	<meta property="og:image:width" content="640" />
	<meta property="og:image:height" content="480" />
	
	<link rel="stylesheet"  href="/css/jquery-ui.css"/>
	<link rel="stylesheet"  href="/css/template2.css"/>
	<!--link rel="stylesheet"  href="/css/font-awesome.min.css"/-->
	<script>$=function(a){$.h.push(a)};$.h=[];$$=$</script>
</head>
<body>
<? include 'email.inc'; ?>